@startuml
'https://plantuml.com/sequence-diagram

!theme reddress-darkblue

autonumber

Request -> Company: receives a request(process())
activate Request
activate Company

Company -> Admission:  Verified the client and membership (verified)
activate Admission

Admission -> Membership: check the limits of the client
activate Membership
deactivate Membership

Admission -> Payment: check if the client have debt
activate Payment

Payment --> Admission: return the debt
deactivate Payment

Admission --> Company: Verified response
deactivate Admission

Company -> SearchRobot: Search a robot for the job
activate SearchRobot
SearchRobot -> Robot:check the requests
activate Robot
deactivate Robot

SearchRobot --> Company: return the robot for the job
deactivate SearchRobot

Company -> Payment: update the debt
activate Payment
deactivate Payment

Company -> DataBaseRobot: update the requests of the robot
activate DataBaseRobot
deactivate DataBaseRobot

Company --> Request: return a receipt with the date and the service
deactivate Company




'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response

'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml